Repository MatinAfzal/Alien-invasion, pull requests merged in 2025-05, with the labels that each got.

#65 Add a region manager system, and 15 new regions
  alien_invasion.py
  data/assets/background/CopyRight.txt
  data/assets/background/starfield/1.png
  data/assets/background/starfield/2.png
  data/assets/background/starfield/3.png
  data/assets/background/starfield/4.png
  data/assets/background/starfield/5.png
  data/assets/background/verdant expanse/1.png
  data/assets/background/verdant expanse/2.png
  data/assets/background/verdant expanse/3.png
  data/assets/background/verdant expanse/4.png
  data/assets/background/verdant expanse/5.png
  data/assets/background/violet void/1.png
  data/assets/background/violet void/2.png
  data/assets/background/violet void/3.png
  data/assets/background/violet void/4.png
  data/assets/background/violet void/5.png
  data/assets/images/space.jpg
  data/assets/images/space1.png
  data/assets/images/space2.jpg
  data/assets/images/space3.png
  src/game_functions.py
  src/region.py
Labels: enhancement

#69 Add new power-ups: spread, double, healing
  alien_invasion.py
  data/assets/sprites/bullet/power_bullet.png
  data/assets/sprites/power/power1.png
  data/assets/sprites/power/power2.png
  data/assets/sprites/power/power3.png
  src/bullet.py
  src/entities/items/power/__init__.py
  src/game_functions.py
  src/ship.py
Labels: enhancement

#70 Better collisions
  src/alien.py
  src/bullet.py
  src/entities/items/heart/__init__.py
  src/entities/items/power/__init__.py
  src/entities/items/shield/__init__.py
  src/game_functions.py
  src/settings/__init__.py
  src/ship.py
Labels: enhancement, trivial change

#71 Add World for better organizing and cleaner main game class
  alien_invasion.py
  main.py
  src/game.py
  src/game_functions.py
  src/world.py
Labels: enhancement, Under review

#72 Sound manager system
  src/animation.py
  src/game.py
  src/game_functions.py
  src/resources/sound_manager.py
Labels: enhancement, Under review
