Repository MatinAfzal/Alien-invasion, pull requests merged in 2025-01, with the labels that each got.

#2 Adding the ability to shoot bullets for aliens
  alien_invasion.py
  data/assets/sprites/ship.png
  src/bullet.py
  src/game_functions.py
  src/settings.py
Labels: enhancement

#5 added main menu, added game over screen, added settings, some bugs fixed, improved aliens, ...
  alien_invasion.py
  data/assets/sounds/cargo_collect.ogg
  data/assets/sprites/alien_bullet.png
  data/assets/sprites/ship.png
  data/game_settings.json
  data/settings.json
  src/alien_invasion.py
  src/bullet.py
  src/debug.py
  src/game_functions.py
  src/input_handler.py
  src/menu_ui.py
  src/scoreboard.py
  src/settings.py
  src/ship.py
Labels: enhancement

#7 Add alien l2
  src/alien.py
  src/game_functions.py
  src/settings.py
Labels: enhancement

#18 Feat/player lives
  alien_invasion.py
  data/assets/hearts/empty_heart.png
  data/assets/hearts/full_heart.png
  src/button.py
  src/game_functions.py
  src/health.py
  src/scoreboard.py
  src/settings.py
  src/ship.py
Labels: bug, enhancement

#22 Feat/increase health
  alien_invasion.py
  src/game_functions.py
  src/health.py
  src/heart.py
  src/settings.py
Labels: enhancement

#29 Added ship mouse control
  src/bullet.py
  src/game_functions.py
  src/ship.py
Labels: enhancement

#33 Bullets go off-screen bug fix
  src/game_functions.py
Labels: fix

#34 Code improvement
  src/alien.py
  src/bullet.py
  src/game_functions.py
Labels: trivial change

#36 Spawn aliens from any edge and automatically move them toward the ship.
  alien_invasion.py
  src/alien.py
  src/game_functions.py
  src/settings.py
Labels: enhancement

#40 Code cleanup
  alien_invasion.py
  bullet.py
  src/alien.py
  src/bullet.py
  src/game_functions.py
  src/game_stats.py
  src/health.py
  src/heart.py
  src/scoreboard.py
  src/settings.py
Labels: trivial change

#41 Implement Input system
  alien_invasion.py
  src/game_functions.py
  src/input.py
  src/ship.py
Labels: enhancement

#42 Better button
  alien_invasion.py
  data/assets/sounds/CopyRight.txt
  data/assets/sounds/button_clicked.mp3
  src/button.py
  src/game_functions.py
Labels: enhancement
